[build-system]
# These are the assumed default build requirements from pip:
# https://pip.pypa.io/en/stable/reference/pip/#pep-517-and-518-support
requires = ["setuptools>=43.0.0", "wheel","PyMySQL>=0.9.3","SQLAlchemy>=1.4.32"]
build-backend = "setuptools.build_meta"
